version: "3.3"
services:
  amb-mediators:
    build: .
    command: "true"
    env_file: ./deploy/.env
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "true"
    env_file: ./deploy/.env